import type { CasinoFeature, CasinoInput } from './types.js';

/**
 * Single source of truth — only real, verified US sweepstakes casino operators.
 * Used for initial seed, catalog reset, and discovery curated list.
 */
export const VERIFIED_CASINO_SEEDS: CasinoInput[] = [
  {
    name: 'Stake.us',
    url: 'https://stake.us',
    description: 'Popular sweepstakes casino with slots, live dealer games, and daily bonuses. Email signup, no phone required.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'live_games', 'instant_play', 'vpn_blocked', 'geo_restricted', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Daily login bonus + welcome offer',
    rating: 4.5,
    verified: true,
  },
  {
    name: 'Chumba Casino',
    url: 'https://www.chumbacasino.com',
    description: 'OG sweepstakes casino with classic slots and table games. Simple email registration.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'table_games', 'vpn_allowed', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Free sweeps coins on signup',
    rating: 4.2,
    verified: true,
  },
  {
    name: 'LuckyLand Slots',
    url: 'https://www.luckylandslots.com',
    description: 'Slot-focused sweepstakes platform with no phone verification needed.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'vpn_allowed'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Welcome bonus sweeps coins',
    rating: 4.0,
    verified: true,
  },
  {
    name: 'Pulsz',
    url: 'https://www.pulsz.com',
    description: 'Sweepstakes casino with slots, table games, and social features.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'table_games', 'vpn_allowed', 'pragmatic_play'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Free coins on registration',
    rating: 4.1,
    verified: true,
  },
  {
    name: 'McLuck',
    url: 'https://www.mcluck.com',
    description: 'Modern sweepstakes casino with slots and live-style games. Quick email signup.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'live_games', 'vpn_allowed', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Sign-up bonus available',
    rating: 4.0,
    verified: true,
  },
  {
    name: 'High 5 Casino',
    url: 'https://www.high5casino.com',
    description: 'Sweepstakes platform known for unique slot titles and easy registration.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'vpn_allowed', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Daily rewards program',
    rating: 3.9,
    verified: true,
  },
  {
    name: 'Fortune Coins',
    url: 'https://fortunecoins.com',
    description: 'Sweepstakes casino with slots and fish games. No phone needed to start.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'vpn_allowed', 'daily_bonus', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Welcome package with free coins',
    rating: 3.8,
    verified: true,
  },
  {
    name: 'Global Poker',
    url: 'https://www.globalpoker.com',
    description: 'Sweepstakes poker room with tournaments. Email-only signup available.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'table_games', 'poker', 'vpn_allowed'],
    signupRequirements: ['Email', 'Password'],
    bonusInfo: 'Free gold coins on signup',
    rating: 4.0,
    verified: true,
  },
  {
    name: 'WOW Vegas',
    url: 'https://www.wowvegas.com',
    description: 'Sweepstakes casino with slots and live dealer. Email signup, no phone.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'live_games', 'vpn_allowed', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 4.1,
    verified: true,
  },
  {
    name: 'Modo.us',
    url: 'https://modo.us',
    description: 'Social sweepstakes with slots and arcade games.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'vpn_allowed', 'signup_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.8,
    verified: true,
  },
  {
    name: 'Spree Casino',
    url: 'https://spree.com',
    description: 'Sweepstakes slots and instant win games.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'instant_play', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.9,
    verified: true,
  },
  {
    name: 'Crown Coins Casino',
    url: 'https://crowncoinscasino.com',
    description: 'Sweepstakes slots and social gaming.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'signup_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.7,
    verified: true,
  },
  {
    name: 'Jackpota',
    url: 'https://www.jackpota.com',
    description: 'Slots and daily rewards.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'daily_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.8,
    verified: true,
  },
  {
    name: 'Funzpoints',
    url: 'https://funzpoints.com',
    description: 'Unique slots, easy signup.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.7,
    verified: true,
  },
  {
    name: 'Zula Casino',
    url: 'https://zulacasino.com',
    description: 'Slots and fish games.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'fish_games'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.6,
    verified: true,
  },
  {
    name: 'Sportzino',
    url: 'https://sportzino.com',
    description: 'Sports and casino hybrid.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'sports', 'slots', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.9,
    verified: true,
  },
  {
    name: 'Real Prize',
    url: 'https://realprize.com',
    description: 'Slots and prize redemptions.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.7,
    verified: true,
  },
  {
    name: 'Hello Millions',
    url: 'https://www.hellomillions.com',
    description: 'Slots, no phone signup.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'pragmatic_play', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.8,
    verified: true,
  },
  {
    name: 'SpinBlitz',
    url: 'https://spinblitz.com',
    description: 'Slots with instant play.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'instant_play'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.6,
    verified: true,
  },
  {
    name: 'Golden Hearts Games',
    url: 'https://goldenheartsgames.com',
    description: 'Charity-linked social casino.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.6,
    verified: true,
  },
  {
    name: 'Fliff',
    url: 'https://www.getfliff.com',
    description: 'Sweepstakes sports picks app.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'sports', 'mobile_app', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.7,
    verified: true,
  },
  {
    name: 'Baba Casino',
    url: 'https://babacasino.com',
    description: 'Sweepstakes slots platform.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
  {
    name: 'Chip N Win',
    url: 'https://chipnwin.com',
    description: 'Social casino with sweeps coins.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.3,
    verified: true,
  },
  {
    name: 'Lucky Bird',
    url: 'https://luckybird.io',
    description: 'Crypto-friendly social casino.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'crypto'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.5,
    verified: true,
  },
  {
    name: 'Pulsz Bingo',
    url: 'https://www.pulszbingo.com',
    description: 'Bingo and sweeps coin games.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'bingo', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.5,
    verified: true,
  },
  {
    name: 'Megabonanza',
    url: 'https://megabonanza.com',
    description: 'Sweeps slots platform.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'new_casino'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
  {
    name: 'Moonspin',
    url: 'https://moonspin.us',
    description: 'Social sweeps with slot variety.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.5,
    verified: true,
  },
  {
    name: 'Tao Fortune',
    url: 'https://taofortune.com',
    description: 'Sweepstakes slots with daily rewards.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'daily_bonus', 'signup_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.7,
    verified: true,
  },
  {
    name: 'NoLimitCoins',
    url: 'https://nolimitcoins.com',
    description: 'Sweepstakes casino with slots and fish games.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'fish_games'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.6,
    verified: true,
  },
  {
    name: 'Rolling Riches',
    url: 'https://rollingriches.com',
    description: 'Sweepstakes slots with wheel bonuses.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'wheel_spin', 'welcome_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.5,
    verified: true,
  },
  {
    name: 'PlayFame',
    url: 'https://www.playfame.com',
    description: 'Social sweeps casino with slots.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'pragmatic_play'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.6,
    verified: true,
  },
  {
    name: 'Yay Casino',
    url: 'https://www.yaycasino.com',
    description: 'Sweepstakes slots and social gaming.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'signup_bonus'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.5,
    verified: true,
  },
  {
    name: 'Lonestar Casino',
    url: 'https://www.lonestarcasino.com',
    description: 'Texas-themed sweepstakes casino.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'multi_state'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
  {
    name: 'Sweepslots',
    url: 'https://sweepslots.com',
    description: 'Slot-focused sweepstakes platform.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
  {
    name: 'Speed Sweeps',
    url: 'https://speedsweeps.com',
    description: 'Fast sweepstakes slot action.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots', 'instant_play'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
  {
    name: 'Acorn Fun',
    url: 'https://acornfun.com',
    description: 'Social sweeps gaming platform.',
    features: ['sweepstakes', 'no_phone', 'email_only', 'slots'],
    signupRequirements: ['Email', 'Password'],
    rating: 3.4,
    verified: true,
  },
];

/** Curated list shape for discovery engine (derived from verified seeds). */
export function getVerifiedCuratedDiscoveries(): Array<{
  name: string;
  url: string;
  description: string;
  features: CasinoFeature[];
  signupRequirements: string[];
  bonusInfo?: string;
  rating?: number;
  source: string;
}> {
  return VERIFIED_CASINO_SEEDS.map((c) => ({
    name: c.name,
    url: c.url,
    description: c.description || '',
    features: c.features || [],
    signupRequirements: c.signupRequirements || ['Email', 'Password'],
    bonusInfo: c.bonusInfo,
    rating: c.rating,
    source: 'verified',
  }));
}
